New Project for Database and basic Classes
jacob-b-labs/biletmajster-backend pull request #5
Opened 2023-03-19 19:28 UTC by WasilewskiJakub

2023-03-26 21:50 UTC, complikator requested changes
Please clean up

2023-04-01 08:56 UTC, WasilewskiJakub reviewed
.Net6 changed on .Net 7

2023-04-01 09:39 UTC, complikator approved these changes

2023-04-01 11:11 UTC, WasilewskiJakub reviewed
Changes

2023-04-01 11:13 UTC, merged